version: '2'
services:
  prjctr_l22_php:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    container_name: prjctr_l22_php
    ports:
      - "9000:9000"
    depends_on:
      - prjctr_l22_redis
      - prjctr_l22_mysql
    volumes:
      - ./var/www:/var/www
      - ./etc/php-fpm.d/:/usr/local/etc/php-fpm.d/
      - phpsocket:/var/run
  prjctr_l22_mysql:
    image: mysql
    container_name: prjctr_l22_mysql
    restart: always
    env_file: .env
    volumes:
      - mysqldsocket:/var/run/mysqld
    ports:
      - "127.0.0.1:3306:3306"
  prjctr_l22_redis:
    image: bitnami/redis
    container_name: prjctr_l22_redis
    env_file: .env
    ports:
      - "6379:6379"
  prjctr_l22_nginx:
    container_name: prjctr_l22_nginx
    image: nginx
    ports:
      - "80:9000"
      - "8080:9000"
    volumes:
      - ./var/www:/var/www/
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - phpsocket:/var/run
    depends_on:
      - prjctr_l22_php
volumes:
  phpsocket:
  mysqldsocket: